### ISSUE TITLE
Refactor fieldsites

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#24]
Discuté avec Fabien, des choses sont à changer au niveau des fieldsites:

Sur /fieldsite (PUT) : (Corriger les autres routes aussi.)
{
    "fieldsite_name": "megagol",
    "envelope": {
        "lon_min": 31,
        "lon_max": 45,
        "lat_min": -5,
        "lat_max": 17
    }
}

Should be : 
Sur /fieldsite**s** (PUT)
{
    "name": "megagol",
    "envelope": {
        "crs_code" : "4326",
        "x_min": 31,
        "x_max": 45,
        "y_min": -5,
        "y_max": 17
    }
}

Corriger les autres routes aussi.

**Comment by rchailan** [comment]
normalement fixé. Mais probleme lors du push.

**Comment by cyril-r** [comment]
Sorry, no :-(

(git remplacé et re-cloné)

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 4 Scala sources and 84 Java sources to /data/MIRMIDON/unstable/mirmidon/LOGIC/api/target/scala-2.10/classes...
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[warn] Note: Some input files use or override a deprecated API.
[warn] Note: Recompile with -Xlint:deprecation for details.
[warn] Note: Some input files use unchecked or unsafe operations.
[warn] Note: Recompile with -Xlint:unchecked for details.
[warn] 1 warning
[info] play - database [default] connected at jdbc:postgresql://127.0.0.1:5432/mirmidon_unstable?searchpath=LOGIC
[error] application - 

! @6l0c81dmd - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[UnsatisfiedLinkError: Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:152) ~[play_2.10.jar:2.2.2]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.2]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10.jar:2.2.2]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10.jar:2.2.2]
    at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /data/MIRMIDON/unstable/mirmidon/LOGIC/core/drmaa-jni/target/libDrmaaJNI.so
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854) ~[na:1.7.0_51]
    at java.lang.Runtime.load0(Runtime.java:795) ~[na:1.7.0_51]
    at java.lang.System.load(System.java:1062) ~[na:1.7.0_51]
    at org.ggf.drmaa.DrmaaJNI.<clinit>(DrmaaJNI.java:36) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]
    at org.ggf.drmaa.sge.SessionImpl.<init>(SessionImpl.java:39) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]
    at org.ggf.drmaa.sge.SessionFactoryImpl.getSession(SessionFactoryImpl.java:36) ~[mirmidon-drmaa-jni-1.0-UNSTABLE.jar:na]

**Comment by rc-34** [comment]
je sais je suis en train de faire des tests. ca va marcher mais il faut d'abord que je pousse le dernier commit. Pour l'heure je n'arrive pas a avoir la connection à la db.. surcharge ?

**Comment by rchailan** [comment]
Probleme drmaa. Ce n'est pas la bonne issue.

**Comment by cyril-r** [comment]
Il y à un problème lors de l'appel à GET /fieldsites

La méthode pour créer un fieldsite fonctionne bien avec la nouvelle envelope, mais lorsque je veux afficher les fieldsites existants, une partie de l'ancienne envelope m'est retournée :

``` json
{
    "2": {
        "fieldsite_id": 2,
        "name": "megagol",
        "creation_date": "Wed Jan 21 10:24:46 CET 2015",
        "envelope": {
            "crs_code": "4236",
            "lon_min": 31,
            "lon_max": 45,
            "lat_min": 31,
            "lat_max": 45
        }
    }
}
```

**Comment by rchailan** [comment]
mea culpa. je viens de pusher le fix.

**Comment by cyril-r** [comment]
@jhuon me fait remarquer que la route /fieldsite (PUT) devrait être /fieldsite**s** (PUT), un petit oubli à fixer.

**Comment by rchailan** [comment]
Non c'était volontaire. Pcq je trouvais ca illogique d'ajouter 1 filedsite et de mettre un "s" à fieldsite et j'ai oubilé de vous demander votre avis. J'ai corrigé selon vos expectations. 
C'est pushé.
