### ISSUE TITLE
Aggregation WW3 non fonctionnelle

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#40]
Lorsque je tente de créer une aggregation WW3 j'ai aussi une exception.
(note: fichier utilisé = un de ceux que tu m'a donné hier).

Json envoyé:

``` json
{
    "name": "WW3 Output",
    "description": "Output run 1",
    "phenomena": [
        "wave-significant-height"      
    ],
    "files": [ "/test/sf_ww3/20130303_123003.nc"
                     ],
    "files_url_protocol": "file"
}
```

Retour constellation

```
http://localhost:8092/constellation/WS/wps/symphonie-builder?VERSION=1.0.0&SERVICE=WPS&IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Aaggregator%3Aimport-netcdf-ww3-regular&REQUEST=DescribeProcess
```

Retour API nul (pas de nouvelle ligne de log).

**Comment by fretif** [comment]
As-tu plus d'infos, quel est le code retour http ?
Rien de plus côté constell ?

---- Le ven., 30 janv. 2015 12:31:46 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Lorsque je tente de créer une aggregation WW3 j'ai aussi une exception.
 (note: fichier utilisé = un de ceux que tu m'a donné hier).
 Json envoyé:
 { "name": "WW3 Output", "description": "Output run 1", "phenomena": [ "wave-significant-height" ], "files": [ "/test/sf_ww3/20130303_123003.nc" ], "files_url_protocol": "file" }
 Retour constellation
 http://localhost:8092/constellation/WS/wps/symphonie-builder?VERSION=1.0.0&amp;SERVICE=WPS&amp;IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Aaggregator%3Aimport-netcdf-ww3-regular&amp;REQUEST=DescribeProcess  Retour API null (pas de nouvelle ligne de log).
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Après la suppression du dossier (issue #39 ) et avoir relancé, voila ce que j'ai en sortie:

Log constellation:

```
http://localhost:8092/constellation/WS/wps/aggregator?VERSION=1.0.0&SERVICE=WPS&IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Aaggregator%3Aimport-netcdf-ww3-regular&REQUEST=DescribeProcess
http://localhost:8092/constellation/WS/wps/aggregator
Process Execute : urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular
getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/718447e8-9fd5-4b69-bf1a-e0a8d595c76c
Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is started.
/opt/tomcat-7.0.50-unstable/temp/aggregation6733760965632028033
Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is finished.
getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/718447e8-9fd5-4b69-bf1a-e0a8d595c76c

```

**Comment by fretif** [comment]
OK, et côté play ?

---- Le ven., 30 janv. 2015 14:16:36 +0100 cyril-r&lt;notifications@github.com&gt; a écrit ---- 

Après la suppression du dossier (issue #39 ) et avoir relancé, voila ce que j'ai en sortie:
 http://localhost:8092/constellation/WS/wps/aggregator?VERSION=1.0.0&amp;SERVICE=WPS&amp;IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Aaggregator%3Aimport-netcdf-ww3-regular&amp;REQUEST=DescribeProcess http://localhost:8092/constellation/WS/wps/aggregator Process Execute : urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/718447e8-9fd5-4b69-bf1a-e0a8d595c76c Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is started. /opt/tomcat-7.0.50-unstable/temp/aggregation6733760965632028033 Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is finished. getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/718447e8-9fd5-4b69-bf1a-e0a8d595c76c  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Nouvel essai après redéploiement, j'obtiens en réponse une exception (page rouge)

Logs play!:

```
2015-02-03 11:50:58,628 - [DEBUG] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular* Executes the process with

2015-02-03 11:50:58,629 - [DEBUG] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular*Inputs :{dim=3, files=http://p4x-650.gateworld.fr:9082/explorer/media?token=2902c346-0826-4116-ba18-183af7ed71be, phenomena=wave-significant-height, description=Output run 1, name=WW3 Output, fieldsite=4, files_url_protocol=file}

2015-02-03 11:50:58,629 - [DEBUG] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular*Ouputs :{}

2015-02-03 11:50:58,698 - [INFO] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular* Process id : 61

2015-02-03 11:50:58,723 - [ERROR] - from application in play-akka.actor.default-dispatcher-5 
None ftp server passive ports were settled

2015-02-03 11:50:58,744 - [ERROR] - from application in play-akka.actor.default-dispatcher-5 
None ftp server passive ports were settled

2015-02-03 11:50:58,756 - [ERROR] - from play in play-internal-execution-context-3 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2015-02-03 11:50:58,794 - [ERROR] - from application in play-internal-execution-context-3 


! @6l47p00il - Internal server error, for (POST) [/aggregations/netcdf-ww3-regular] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.2]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.2]
    at scala.Option.map(Option.scala:145) [scala-library.jar:na]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257) [play_2.10.jar:2.2.2]
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
    at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.2]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.NullPointerException: null
    at controllers.m_core_wps.DefaultProcessController.executeWPS(DefaultProcessController.java:213) ~[classes/:na]
    at controllers.m_aggregator.ImportFromNetcdfWW3.execute(ImportFromNetcdfWW3.java:122) ~[classes/:na]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(routes_routing.scala:415) ~[classes/:na]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(routes_routing.scala:415) ~[classes/:na]
    at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.2]
    at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.2]
    at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.2]
    at play.GlobalSettings$1.call(GlobalSettings.java:64) ~[play_2.10.jar:2.2.2]
    at play.mvc.Security$AuthenticatedAction.call(Security.java:45) ~[play_2.10.jar:2.2.2]
    at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.2]
    at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.2]
    at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.2]
    at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.2]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
    at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.2]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
    ... 4 common frames omitted

2015-02-03 11:50:59,887 - [ERROR] - from application in Thread-11 
[WPSProcessManager] Succeed error 5 :Error while adding the aggregation: /opt/tomcat-7.0.50-unstable/temp/aggregation1976886055013462504/wave-significant-height.nc (Aucun fichier ou dossier de ce type)
```

Côté Constellation: 

```
http://localhost:8092/constellation/WS/wps/aggregator?VERSION=1.0.0&SERVICE=WPS&IDENTIFIER=urn%3Aogc%3Acstl%3Awps%3Aaggregator%3Aimport-netcdf-ww3-regular&REQUEST=DescribeProcess
http://localhost:8092/constellation/WS/wps/aggregator
Process Execute : urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular
getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/2f9baed8-8ade-410e-9118-0a2904ed4fdf
Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is started.
/opt/tomcat-7.0.50-unstable/temp/aggregation1976886055013462504
Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is finished.
getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/2f9baed8-8ade-410e-9118-0a2904ed4fdf


```

**Comment by cyril-r** [comment]
Après redéploiement/reset DB/populator, lors d'une aggrégation, j'ai un retour HTTP 200 (ok).

Lorsque je liste les aggregations voici ce que je récupère:

``` json
[
    {
        "name": "WW3 Output",
        "status": "failed",
        "pourcent": 100,
        "creation_date": "2015-2-3 15:31:18",
        "updated_date": "2015-2-3 15:31:19"
    }
]
```

Logs play!

```
2015-02-03 15:31:18,790 - [DEBUG] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular* Executes the process with

2015-02-03 15:31:18,791 - [DEBUG] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular*Inputs :{dim=3, files=http://p4x-650.gateworld.fr:9082/explorer/media?token=f990b265-0fb5-44ec-8d41-ca34bcc16f8e, phenomena=wave-significant-height, description=Output run 1, name=WW3 Output, fieldsite=1, files_url_protocol=file}

2015-02-03 15:31:18,791 - [DEBUG] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular*Ouputs :{}

2015-02-03 15:31:18,861 - [INFO] - from application in play-akka.actor.default-dispatcher-5 
[aggregator] *Import results from output of WW3 regular* Process id : 1

2015-02-03 15:31:20,059 - [ERROR] - from application in Thread-11 
[WPSProcessManager] Succeed error 5 :Error while adding the aggregation: /opt/tomcat-7.0.50-unstable/temp/aggregation8517055769940314706/wave-significant-height.nc (Aucun fichier ou dossier de ce type)
```

Logs constellation:

```
http://localhost:8092/constellation/WS/wps/aggregator
Process Execute : urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular
getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/b8f1ba94-51f3-48da-9d03-3d0c26487fdf
Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is started.
/opt/tomcat-7.0.50-unstable/temp/aggregation8517055769940314706
Process urn:ogc:cstl:wps:aggregator:import-netcdf-ww3-regular is finished.
getResource host=localhost:8092 url=/constellation/webdav/wps-aggregator/b8f1ba94-51f3-48da-9d03-3d0c26487fdf

```

Un tree sur **/opt/tomcat-7.0.50-unstable/temp/aggregation8517055769940314706/**

```
/opt/tomcat-7.0.50-unstable/temp/aggregation8517055769940314706/
├── graphiques
│   └── 20130303_123003.nc
├── myConfig.conf
└── script.sh

1 directory, 3 files

```

**Comment by cyril-r** [comment]
cleanup close
