### ISSUE TITLE
API ne démarre plus

### ISSUE THREAD

**Issue by cyril-r** [MirmidonDev/mirmidon_unstable#46]
Suite au dernier push ( b4dd83283ffed9694a1646df981dd14c2ca9c6cb ), l'API ne démarre plus, voici les logs play!

Console:

```
[error] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7'
[error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_core_wps/DefaultProcessController.java:209: error: constructor WPSMonitor in class WPSMonitor cannot be applied to given types;
[error]             processMonitor = new WPSMonitor(statusLocation, this,inputs,user);
[error]                              ^
[error]   required: URL,ProcessController,MUser
[error]   found: URL,DefaultProcessController,Map<String,Object>,MUser
[error]   reason: actual and formal argument lists differ in length
[error] Note: Some input files use or override a deprecated API.
[error] Note: Recompile with -Xlint:deprecation for details.
[error] Note: Some input files use unchecked or unsafe operations.
[error] Note: Recompile with -Xlint:unchecked for details.
[error] 1 error
[error] 1 warning
[error] (compile:compile) javac returned nonzero exit code

Cannot start with errors.

```

Logfile:

```
2015-02-12 10:36:09,013 - [ERROR] - from application in New I/O worker #2 


! @6l6l0kink - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[error: constructor WPSMonitor in class WPSMonitor cannot be applied to given types;]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
    at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
    at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.2]
    at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.2]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
```

**Comment by rchailan** [comment]
Fixé temporairement. Je ne garantis pas le bon fonctionnement du monitoring des WPS. Mais ca débloque pour compiler. 
Il faudra aussi avant de relancer se faire un petit "play clean". De mon côté j'ai observé des comportements étranges qui ont été fixés une fois que le cache de play a ete reloadé de cette facon.

**Comment by fretif** [comment]
Fixed

---- Le jeu., 12 févr. 2015 10:52:49 +0100 cyril-r &lt;notifications@github.com&gt; a écrit ---- 

Suite au dernier push ( b4dd83283ffed9694a1646df981dd14c2ca9c6cb ), l'API ne démarre plus, voici les logs play!
 Console:
 [error] warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.7' [error] /data/MIRMIDON/unstable/mirmidon/LOGIC/api/app/controllers/m_core_wps/DefaultProcessController.java:209: error: constructor WPSMonitor in class WPSMonitor cannot be applied to given types; [error] processMonitor = new WPSMonitor(statusLocation, this,inputs,user); [error] ^ [error] required: URL,ProcessController,MUser [error] found: URL,DefaultProcessController,Map&lt;String,Object&gt;,MUser [error] reason: actual and formal argument lists differ in length [error] Note: Some input files use or override a deprecated API. [error] Note: Recompile with -Xlint:deprecation for details. [error] Note: Some input files use unchecked or unsafe operations. [error] Note: Recompile with -Xlint:unchecked for details. [error] 1 error [error] 1 warning [error](compile:compile) javac returned nonzero exit code Cannot start with errors.  Logfile:
 2015-02-12 10:36:09,013 - [ERROR] - from application in New I/O worker #2 ! @6l6l0kink - Internal server error, for (GET) [/] -&gt; play.PlayExceptions$CompilationException: Compilation error[error: constructor WPSMonitor in class WPSMonitor cannot be applied to given types;] at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na] at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na] at scala.Option.map(Option.scala:145) ~[scala-library.jar:na] at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na] at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na] at scala.Option.map(Option.scala:145) ~[scala-library.jar:na] at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na] at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na] at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na] at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na] at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.2.2] at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10.jar:2.2.2] at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na] at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na] at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na] at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na] at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na] at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na] at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]  —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
@fretif je redéploie le code à nouveau?

@rc-34 : concernant le play clean, tu veux que je l'intègre au script d'update de code ? elle serais à faire juste après avoir copié le code et avant de lancer l'API, right?

**Comment by fretif** [comment]
oui test en redéployant, si ca ne marche pas, vois avec Romain.

---- Le jeu., 12 févr. 2015 11:47:36 +0100 cyril-r &lt;notifications@github.com&gt; a écrit ---- 

@fretif je redéploie le code à nouveau?
 @rc-34 : concernant le play clean, tu veux que je l'intègre au script d'update de code ? elle serais à faire juste après avoir copié le code et avant de lancer l'API, right?
 —
Reply to this email directly or view it on GitHub.

_.-~-._.-~-._.-~-._.-~-._.-~-._ 
PhD. Fabien Rétif
Géosciences Montpellier
UMR 5243 - CC 60
Universite Montpellier II
Bat 22 - Bureau 468
Place Eugène Bataillon
34095 Montpellier Cedex 5
France
Tel : +33 (0)4.67.14.35.85
_.-~-._.-~-._.-~-._.-~-._.-~-._

**Comment by cyril-r** [comment]
Fixed.
